const GRADES = ["NG", "D", "C", "C+", "B", "B+", "A", "A+"].reverse();

const SUB_12_DETAILS = [
    {
        code: "0021",
        name: "Com.Nepali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "3",
        theory_credit: "2.25",
        internal_credit: "0.75",
    },
    {
        code: "0041",
        name: "Com.English",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0061",
        name: "Com.Social Studies & Life Skill",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0081",
        name: "Com.Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0121",
        name: "Sanskrit Rachana",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0181",
        name: "Sanskrit Bhasha & Byakaran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0221",
        name: "Baudh Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0321",
        name: "Urdu Byakaran & Sahitya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "1021",
        name: "Physics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1041",
        name: "Accounting",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1061",
        name: "Rural Development",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1101",
        name: "Nepalese Legal system",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1121",
        name: "Painting",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1181",
        name: "Instructional Pedagogy and Evaluation",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1201",
        name: "Psychology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1221",
        name: "History",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1241",
        name: "Gender Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1261",
        name: "Hospitality Management",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1281",
        name: "Agronomy",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1301",
        name: "Naturopathy",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1321",
        name: "Human Value Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2021",
        name: "Biology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2041",
        name: "Education and Development",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2061",
        name: "Geography",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2101",
        name: "Legal Drafting",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "2121",
        name: "Sociology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2141",
        name: "Ayurbed",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "2161",
        name: "Business Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2181",
        name: "Linguistics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2201",
        name: "Political Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2221",
        name: "Philosophy",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2241",
        name: "Population Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2261",
        name: "Horticulture (Fruit, Vegetable, Flower & Mushroom)",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2281",
        name: "Food and Nutrition",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2301",
        name: "Dance",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "2321",
        name: "History of Arts",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3021",
        name: "Chemistry",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3041",
        name: "Economics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3061",
        name: "Tourism and Mountaineering Studies",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3081",
        name: "Marketing",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3101",
        name: "Gerontology and Care Taking Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3121",
        name: "Yog",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3141",
        name: "Vocal/Instrumetal",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3161",
        name: "Sewing and Knitting",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3201",
        name: "Civil and Criminal law and justice",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3221",
        name: "Culinary Arts",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3241",
        name: "Culture",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3261",
        name: "Fashion Designing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3281",
        name: "Film and Dacumentry",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3301",
        name: "Live Stock, Poultry and Fish Farming",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3321",
        name: "Nepali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3341",
        name: "English",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3361",
        name: "Maithali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3381",
        name: "Newari",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3401",
        name: "Hindi",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3421",
        name: "Chinease",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3441",
        name: "Jerman",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3461",
        name: "Japanease",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3481",
        name: "Korean",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3501",
        name: "Urdu",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3521",
        name: "Bhojpuri",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3541",
        name: "French",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3561",
        name: "Hibru",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3581",
        name: "Arabic",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3601",
        name: "Sanskrit",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3621",
        name: "Applied Arts",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4021",
        name: "Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4041",
        name: "Applied mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4061",
        name: "Business Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4081",
        name: "Human rights",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4101",
        name: "Library and Information Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4121",
        name: "Home Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4141",
        name: "Environment Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4161",
        name: "General Law",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4181",
        name: "Finance",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4201",
        name: "Co-operative management",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4221",
        name: "Buddhist Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4241",
        name: "Sculpture",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4261",
        name: "Singing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4281",
        name: "Computer Science",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4301",
        name: "Sericulture and Bee Keeping",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4321",
        name: "Beautician and Hair Dressing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4341",
        name: "Medicinal Herbals",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4361",
        name: "Plumbing and Wiring",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4381",
        name: "Internal Decoration",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4401",
        name: "Hotel Management",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4421",
        name: "Mass Communication",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4441",
        name: "Health and Physical Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4461",
        name: "Sports Science",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4481",
        name: "Social Studies & Life Skill Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5021",
        name: "Shuklayajurbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5041",
        name: "Sambed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5061",
        name: "Rigbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5081",
        name: "Atharbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5101",
        name: "Grammar",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5121",
        name: "Sidhant Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5141",
        name: "Nayay",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5161",
        name: "Phyloshophy",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5181",
        name: "Sanskrit Sahitya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5201",
        name: "Itihas Puran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5221",
        name: "Nitishastra",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5281",
        name: "Baudh Karma Kanda",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5321",
        name: "Karmakand",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5341",
        name: "Falit Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5381",
        name: "Bastushastra",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6021",
        name: "Baudh Darshan",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6121",
        name: "Kuran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6221",
        name: "Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6241",
        name: "Bhaisjya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6261",
        name: "Shilpa Vidhya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6321",
        name: "Pali Language",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6341",
        name: "Bhot Language",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6521",
        name: "Hadis & Asule Hadis",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6621",
        name: "Miras Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
];

const SUB_11_DETAILS = [
    {
        code: "0011",
        name: "Com.Nepali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "3",
        theory_credit: "2.25",
        internal_credit: "0.75",
    },
    {
        code: "0031",
        name: "Com.English",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0051",
        name: "Com.Social Studies & Life Skill",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0071",
        name: "Com.Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0111",
        name: "Sanskrit Rachana",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0171",
        name: "Sanskrit Bhasha & Byakaran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "0211",
        name: "Baudh Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "0311",
        name: "Urdu Byakaran & Sahitya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "4",
        theory_credit: "3.00",
        internal_credit: "1.00",
    },
    {
        code: "1011",
        name: "Physics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1031",
        name: "Accounting",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1051",
        name: "Rural Development",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1071",
        name: "Jurispudence and Legal Theories",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1111",
        name: "Painting",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1151",
        name: "Child Development and Learning",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1191",
        name: "Psychology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1211",
        name: "History",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1231",
        name: "Gender Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "1251",
        name: "Hospitality Management",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1271",
        name: "Agronomy",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1291",
        name: "Naturopathy",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "1311",
        name: "Human Value Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2011",
        name: "Biology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2031",
        name: "Education and Development",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2051",
        name: "Geography",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2071",
        name: "Procedural Law",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2111",
        name: "Sociology",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2131",
        name: "Ayurbed",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "2151",
        name: "Business Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2171",
        name: "Linguistics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2191",
        name: "Political Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2211",
        name: "Philosophy",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2231",
        name: "Population Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2251",
        name: "Horticulture (Fruit, Vegetable, Flower & Mushroom)",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2271",
        name: "Food and Nutrition",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "2291",
        name: "Dance",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "2311",
        name: "History of Arts",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3011",
        name: "Chemistry",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3031",
        name: "Economics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3051",
        name: "Tourism and Mountaineering Studies",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3071",
        name: "Marketing",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3091",
        name: "Gerontology and Care Taking Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3111",
        name: "Yog",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3131",
        name: "Vocal/Instrumetal",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3151",
        name: "Sewing and Knitting",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3171",
        name: "Constitutional Law",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3211",
        name: "Culinary Arts",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3231",
        name: "Culture",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3251",
        name: "Fashion Designing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3271",
        name: "Film and Dacumentry",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3291",
        name: "Live Stock, Poultry and Fish Farming",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "3311",
        name: "Nepali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3331",
        name: "English",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3351",
        name: "Maithali",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3371",
        name: "Newari",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3391",
        name: "Hindi",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3411",
        name: "Chinease",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3431",
        name: "Jerman",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3451",
        name: "Japanease",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3471",
        name: "Korean",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3491",
        name: "Urdu",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3511",
        name: "Bhojpuri",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3531",
        name: "French",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3551",
        name: "Hibru",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3571",
        name: "Arabic",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3591",
        name: "Sanskrit",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "3611",
        name: "Applied Arts",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4011",
        name: "Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4031",
        name: "Applied mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4051",
        name: "Business Mathematics",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4071",
        name: "Human rights",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4091",
        name: "Library and Information Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4111",
        name: "Home Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4131",
        name: "Environment Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4151",
        name: "General Law",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4171",
        name: "Finance",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4191",
        name: "Co-operative management",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4211",
        name: "Buddhist Studies",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4231",
        name: "Sculpture",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4251",
        name: "Singing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4271",
        name: "Computer Science",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4291",
        name: "Sericulture and Bee Keeping",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4311",
        name: "Beautician and Hair Dressing",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4331",
        name: "Medicinal Herbals",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4351",
        name: "Plumbing and Wiring",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4371",
        name: "Internal Decoration",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4391",
        name: "Hotel Management",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4411",
        name: "Mass Communication",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4431",
        name: "Health and Physical Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "4451",
        name: "Sports Science",
        full_marks: "50",
        pass_marks: "50",
        total_credits: "5",
        theory_credit: "2.50",
        internal_credit: "2.50",
    },
    {
        code: "4471",
        name: "Social Studies & Life Skill Education",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5011",
        name: "Shuklayajurbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5031",
        name: "Sambed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5051",
        name: "Rigbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5071",
        name: "Atharbed",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5091",
        name: "Grammar",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5111",
        name: "Sidhant Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5131",
        name: "Nayay",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5151",
        name: "Phyloshophy",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5171",
        name: "Sanskrit Sahitya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5191",
        name: "Itihas Puran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5211",
        name: "Nitishastra",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5271",
        name: "Baudh Karma Kanda",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5311",
        name: "Karmakand",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5331",
        name: "Falit Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "5371",
        name: "Bastushastra",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6011",
        name: "Baudh Darshan",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6111",
        name: "Kuran",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6211",
        name: "Jyotish",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6231",
        name: "Bhaisjya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6251",
        name: "Shilpa Vidhya",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6311",
        name: "Pali Language",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6331",
        name: "Bhot Language",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6511",
        name: "Hadis & Asule Hadis",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
    {
        code: "6611",
        name: "Miras Science",
        full_marks: "75",
        pass_marks: "25",
        total_credits: "5",
        theory_credit: "3.75",
        internal_credit: "1.25",
    },
];

const SUB_11_DETAILS_ASC = SUB_11_DETAILS.sort((a, b) =>
    a.name > b.name ? 1 : b.name > a.name ? -1 : 0
);
const SUB_11_COMP_SUBS = SUB_11_DETAILS_ASC.filter(
    (subject) => subject.name.indexOf("Com.") != -1
);

const SUB_12_DETAILS_ASC = SUB_12_DETAILS.sort((a, b) =>
    a.name > b.name ? 1 : b.name > a.name ? -1 : 0
);
const SUB_12_COMP_SUBS = SUB_12_DETAILS_ASC.filter(
    (subject) => subject.name.indexOf("Com.") != -1
);

export {
    SUB_11_DETAILS,
    SUB_12_DETAILS,
    GRADES,
    SUB_11_DETAILS_ASC,
    SUB_11_COMP_SUBS,
    SUB_12_DETAILS_ASC,
    SUB_12_COMP_SUBS,
};
